drop table if exists person CASCADE;
create table person (
    id integer generated by default as identity,
    age integer not null check (age<=100 AND age>=0),
    job varchar(255) not null, name varchar(50) not null,
    ni_number varchar(255), primary key (id)
);
